name: RMW Matrix (FastDDS + CycloneDDS)
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix: { rmw: [rmw_fastrtps_cpp, rmw_cyclonedds_cpp] }
    steps:
      - uses: actions/checkout@v4
      - uses: ros-tooling/setup-ros@v0.7
        with: { required-ros-distributions: jazzy }
      - run: |
          sudo apt-get update
          sudo apt-get install -y ros-jazzy-rmw-cyclonedds-cpp python3-colcon-common-extensions
      - name: rosdep
        shell: bash
        run: |
          source /opt/ros/jazzy/setup.bash
          rosdep update
          rosdep install --from-paths src -y --ignore-src
      - name: Build
        shell: bash
        run: |
          source /opt/ros/jazzy/setup.bash
          colcon build --event-handlers console_direct+
      - name: Test (${{ matrix.rmw }})
        shell: bash
        run: |
          source /opt/ros/jazzy/setup.bash
          source install/setup.bash
          export RMW_IMPLEMENTATION=${{ matrix.rmw }}
          export ROS_DOMAIN_ID=77
          colcon test --packages-select my_rmw_tests_py --event-handlers console_direct+ --return-code-on-test-failure
          colcon test-result --all --verbose
